"""property unique constraint migration

Revision ID: 060467d05388
Revises: 9c43176d4d69
Create Date: 2026-02-11 00:03:12.745679

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '060467d05388'
down_revision: Union[str, Sequence[str], None] = '9c43176d4d69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_property_lat_lng_deleted', 'properties', ['latitude', 'longitude', 'is_deleted'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_property_lat_lng_deleted', 'properties', type_='unique')
    # ### end Alembic commands ###
