"""initial migration

Revision ID: 16f32bdd6f6b
Revises: cfef1150e008
Create Date: 2026-02-10 16:45:05.824019

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "16f32bdd6f6b"
down_revision: Union[str, Sequence[str], None] = "cfef1150e008"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "tenants", ["name"])
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    op.drop_constraint(None, "tenants", type_="unique")
    # ### end Alembic commands ###
