"""add unique constraint on amenity and fix user constraints

Revision ID: 2c05f75bf18d
Revises: 5110c35b3334
Create Date: 2026-02-14 19:53:53.053469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c05f75bf18d'
down_revision: Union[str, Sequence[str], None] = '5110c35b3334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('amenities_name_key'), 'amenities', type_='unique')
    op.create_unique_constraint('uq_amenity_name_is_deleted', 'amenities', ['name', 'is_deleted'])
    op.drop_constraint(op.f('uq_tenant_email'), 'users', type_='unique')
    op.create_unique_constraint('uq_tenant_email', 'users', ['tenant_id', 'email', 'is_deleted'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tenant_email', 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_tenant_email'), 'users', ['tenant_id', 'email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_amenity_name_is_deleted', 'amenities', type_='unique')
    op.create_unique_constraint(op.f('amenities_name_key'), 'amenities', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
