"""username tenant unique constraint migration

Revision ID: 3cb58c241d1a
Revises: 8fd30ec38ca2
Create Date: 2026-02-11 17:49:35.532581

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3cb58c241d1a'
down_revision: Union[str, Sequence[str], None] = '8fd30ec38ca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_tenant_username', 'users', ['tenant_id', 'username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tenant_username', 'users', type_='unique')
    # ### end Alembic commands ###
