"""edit review table

Revision ID: 3f8f29d5f9e1
Revises: 5dc73e2b416c
Create Date: 2026-02-16 12:42:16.185506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f8f29d5f9e1'
down_revision: Union[str, Sequence[str], None] = '5dc73e2b416c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'comment',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'comment',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
