"""add_booking_payment_message_webhook_fixes

Revision ID: 5110c35b3334
Revises: 4db491e3ca5a
Create Date: 2026-02-12 14:30:33.730426

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5110c35b3334'
down_revision: Union[str, Sequence[str], None] = '4db491e3ca5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webhooks', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webhooks', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
