"""add_booking_base_amount_field

Revision ID: 71617293b3f8
Revises: 84db2ca433d5
Create Date: 2026-02-15 17:28:18.992023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71617293b3f8'
down_revision: Union[str, Sequence[str], None] = '84db2ca433d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('base_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'base_amount')
    # ### end Alembic commands ###
