"""replace unique constraint with partial index for user and amenity

Revision ID: 84db2ca433d5
Revises: 2c05f75bf18d
Create Date: 2026-02-14 20:04:10.211871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84db2ca433d5'
down_revision: Union[str, Sequence[str], None] = '2c05f75bf18d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_amenity_name_is_deleted'), 'amenities', type_='unique')
    op.create_index('uq_amenity_name_active', 'amenities', ['name'], unique=True, postgresql_where=sa.text('is_deleted IS FALSE'))
    op.drop_constraint(op.f('uq_tenant_email'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_tenant_username'), 'users', type_='unique')
    op.create_index('uq_tenant_email_active', 'users', ['tenant_id', 'email'], unique=True, postgresql_where=sa.text('is_deleted IS FALSE'))
    op.create_index('uq_tenant_username_active', 'users', ['tenant_id', 'username'], unique=True, postgresql_where=sa.text('is_deleted IS FALSE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_tenant_username_active', table_name='users', postgresql_where=sa.text('is_deleted IS FALSE'))
    op.drop_index('uq_tenant_email_active', table_name='users', postgresql_where=sa.text('is_deleted IS FALSE'))
    op.create_unique_constraint(op.f('uq_tenant_username'), 'users', ['tenant_id', 'username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_tenant_email'), 'users', ['tenant_id', 'email', 'is_deleted'], postgresql_nulls_not_distinct=False)
    op.drop_index('uq_amenity_name_active', table_name='amenities', postgresql_where=sa.text('is_deleted IS FALSE'))
    op.create_unique_constraint(op.f('uq_amenity_name_is_deleted'), 'amenities', ['name', 'is_deleted'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
