"""email tenant unique constraint migration

Revision ID: 8fd30ec38ca2
Revises: 060467d05388
Create Date: 2026-02-11 15:03:32.779193

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8fd30ec38ca2'
down_revision: Union[str, Sequence[str], None] = '060467d05388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_property_lat_lng_deleted'), 'properties', type_='unique')
    op.create_unique_constraint('uq_property_lat_lng_deleted', 'properties', ['tenant_id', 'latitude', 'longitude', 'is_deleted'])
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_unique_constraint('uq_tenant_email', 'users', ['tenant_id', 'email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tenant_email', 'users', type_='unique')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_property_lat_lng_deleted', 'properties', type_='unique')
    op.create_unique_constraint(op.f('uq_property_lat_lng_deleted'), 'properties', ['latitude', 'longitude', 'is_deleted'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
