"""add_dashboard_indexes

Revision ID: dba3d006fd9b
Revises: 3f8f29d5f9e1
Create Date: 2026-02-16 15:50:00.682457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dba3d006fd9b'
down_revision: Union[str, Sequence[str], None] = '3f8f29d5f9e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_bookings_check_in', 'bookings', ['check_in'], unique=False)
    op.create_index('ix_bookings_created_at', 'bookings', ['created_at'], unique=False)
    op.create_index('ix_bookings_tenant_status', 'bookings', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_payments_created_at', 'payments', ['created_at'], unique=False)
    op.create_index('ix_payments_tenant_status', 'payments', ['tenant_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_tenant_status', table_name='payments')
    op.drop_index('ix_payments_created_at', table_name='payments')
    op.drop_index('ix_bookings_tenant_status', table_name='bookings')
    op.drop_index('ix_bookings_created_at', table_name='bookings')
    op.drop_index('ix_bookings_check_in', table_name='bookings')
    # ### end Alembic commands ###
