"""convert lat lng to numeric

Revision ID: eb85b0e01f36
Revises: 747637dc3666
Create Date: 2026-02-15 22:36:40.789703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb85b0e01f36'
down_revision: Union[str, Sequence[str], None] = '747637dc3666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=False))
    op.add_column('properties', sa.Column('review_count', sa.Integer(), nullable=False))
    op.alter_column('properties', 'latitude',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Numeric(precision=10, scale=6),
               existing_nullable=False,
               postgresql_using='latitude::numeric')
    op.alter_column('properties', 'longitude',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Numeric(precision=10, scale=6),
               existing_nullable=False,
               postgresql_using='longitude::numeric')
    op.drop_constraint(op.f('uq_property_lat_lng_deleted'), 'properties', type_='unique')
    op.create_index(op.f('ix_properties_price_per_night'), 'properties', ['price_per_night'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_price_per_night'), table_name='properties')
    op.create_unique_constraint(op.f('uq_property_lat_lng_deleted'), 'properties', ['tenant_id', 'latitude', 'longitude', 'is_deleted'], postgresql_nulls_not_distinct=False)
    op.alter_column('properties', 'longitude',
               existing_type=sa.Numeric(precision=10, scale=6),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('properties', 'latitude',
               existing_type=sa.Numeric(precision=10, scale=6),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('properties', 'review_count')
    op.drop_column('properties', 'rating')
    # ### end Alembic commands ###
